---
# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: nica.dev
vagrant_machine_name: nica
vagrant_ip: 0.0.0.0

drupal_composer_install_dir: "/var/www/drupalvm"

drupalvm_webserver: nginx
nginx_remove_default_vhost: true

drupal_build_composer_project: false
drupal_install_site: false

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  - elasticsearch
  - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  - solr
  # - tideways
  # - upload-progress
  - varnish
  - xdebug
  # - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite
  - php7.1-zip

post_provision_scripts:
  - "{{ config_dir }}/scripts/drupalvm/configure-solr.sh"

php_memory_limit: "512M"

php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1

solr_version: "6.3.0"
