---
# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: nica.dev
vagrant_machine_name: nica
vagrant_ip: 0.0.0.0

drupal_composer_install_dir: "/var/www/drupalvm"

drupal_build_composer_project: false
drupal_install_site: false

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  - elasticsearch
  - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  - solr
  # - tideways
  # - upload-progress
  - varnish
  - xdebug
  # - xhprof

post_provision_scripts:
  - "{{ config_dir }}/scripts/drupalvm/configure-solr.sh"
  #- "{{ config_dir }}/scripts/drupalvm/post-provision.sh"
  # - "../examples/scripts/configure-solr.sh"


# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x", "6.x".
nodejs_version: "6.x"

# Solr Configuration (if enabled above).
solr_version: "6.5.1"
solr_xms: "64M"
solr_xmx: "128M"
